---
- hosts: localhost
  connection: local
  tasks:
    - name: Pull the latest code from the GitHub repository
      git:
        repo: 'https://github.com/paju3125/Flask-App.git'
        dest: /home/runner/work/Flask-App/deploy/Flask_App
        version: master

    - name: Create a virtual environment using venv
      command: python3 -m venv /home/runner/work/Flask-App/deploy/Flask_App/venv
      args:
        creates: /home/runner/work/Flask-App/deploy/Flask_App/venv/bin/activate

    - name: Install dependencies
      command: /home/runner/work/Flask-App/deploy/Flask_App/venv/bin/pip install -r /home/runner/work/Flask-App/deploy/Flask_App/requirements.txt

    - name: Run Flask application tests
      command: >
        /home/runner/work/Flask-App/deploy/Flask_App/venv/bin/python -m pytest
      args:
        chdir: /home/runner/work/Flask-App/deploy/Flask_App
